# Generated by Django 5.2.3 on 2025-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='status',
            field=models.CharField(choices=[('Reprovado', 'Reprovado'), ('Aprovado', 'Aprovado')], default=None, max_length=20, null=True),
        ),
    ]
