# Generated by Django 5.2.3 on 2025-07-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='classe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
