# Generated by Django 5.2.3 on 2025-07-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_matrix',
            field=models.JSONField(default=list, null=True),
        ),
    ]
