# Generated by Django 5.2.3 on 2025-07-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_studentanswer_answer_matrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='N/A', max_length=255, null=True),
        ),
    ]
